openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Patient:
      allOf:
        - $ref: "#/components/schemas/Person"
        - $ref: "#/components/schemas/Employee"
      required:
        - patientId
      properties:
        patientId:
          type: string

    Person:
      required:
        - firstName
        - lastName
        - birthDate
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date

    Employee:
      required:
        - employeeId
        - firstName
        - lastName
      properties:
        employeeId:
          type: string
        firstName:
          type: string
        lastName:
          type: string