openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Article:
      required:
        - gtin
      properties:
        gtin:
          type: integer
          format: int64
          minimum: 1000000000000
          maximum: 9999999999999
          example: 9781234567897