openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Person:
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          type: string
          description: last name
          nullable: true

    FirstName:
      type: string
      description: first name
      nullable: true