openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 50
        lastName:
          type: string
        street:
          type: string
        houseNumber:
          type: integer