openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      required:
        - id
        - username
      properties:
        id:
          type: string
          minLength: 2
        username:
          type: string
        age:
          type: integer
          format: int32
          minimum: 18
          maximum: 199
        email:
          type: string
          nullable: true
    Admin:
      required:
        - id
        - adminname
      properties:
        id:
          type: string
          minLength: 2
        adminname:
          type: string
        level:
          type: integer
          format: int64
          minimum: 1

    AdminOrUser:
      anyOf:
        - $ref: '#/components/schemas/Admin'
        - $ref: '#/components/schemas/User'

    InlinedAnyOf:
      type: object
      required:
        - adminOrUser
      properties:
        adminOrUser:
          anyOf:
            - $ref: '#/components/schemas/Admin'
            - $ref: '#/components/schemas/User'






