openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    AllValueObject:
      type: object
      properties:
        doubleValue:
          $ref: "#/components/schemas/DoubleValue"
        floatValue:
          $ref: "#/components/schemas/FloatValue"
        intValue:
          $ref: "#/components/schemas/IntValue"
        longValue:
          $ref: "#/components/schemas/LongValue"
        stringValue:
          $ref: "#/components/schemas/StringValue"
        email:
          $ref: "#/components/schemas/Email"
    MultipleOfObject:
      type: object
      properties:
        doubleValue:
          $ref: "#/components/schemas/MultipleOfDoubleValue"
        floatValue:
          $ref: "#/components/schemas/MultipleOfFloatValue"
        intValue:
          $ref: "#/components/schemas/MultipleOfIntValue"
        longValue:
          $ref: "#/components/schemas/MultipleOfLongValue"

    NumbersObject:
      type: object
      properties:
        doubleValue:
          type: number
          format: double
        floatValue:
          type: number
          format: float
        intValue:
          type: integer
          format: int32
        longValue:
          type: integer
          format: int64
      minProperties: 2
      maxProperties: 3

    IntegerMemberArray:
      type: object
      required:
        - numbers
      properties:
        numbers:
          type: array
          items:
            type: integer
            format: int32
          minItems: 3
          maxItems: 5

    IntegerPojoArray:
      type: array
      items:
        type: integer
        format: int32
      minItems: 3
      maxItems: 5

    LongMemberArray:
      type: object
      required:
        - numbers
      properties:
        numbers:
          type: array
          items:
            type: integer
            format: int64
          uniqueItems: true

    LongPojoArray:
      type: array
      items:
        type: integer
        format: int64
      uniqueItems: true

    RequiredProperties:
      required:
        - val1
        - val2
      properties:
        val1:
          type: string
        val2:
          type: string
          nullable: true

    Nested:
      required:
        - id
        - obj
      properties:
        id:
          type: string
        obj:
          $ref: "#/components/schemas/AllValueObject"

    DoubleValue:
      type: number
      format: double
      minimum: 5.1
      maximum: 100.5
      exclusiveMaximum: true

    FloatValue:
      type: number
      format: float
      minimum: 200.25
      maximum: 300.5
      exclusiveMaximum: true

    IntValue:
      type: integer
      format: int32
      minimum: -5
      maximum: 22

    LongValue:
      type: integer
      format: int64
      minimum: -122
      maximum: 249

    MultipleOfDoubleValue:
      type: number
      format: double
      multipleOf: 5.5

    MultipleOfFloatValue:
      type: number
      format: float
      multipleOf: 2.25

    MultipleOfIntValue:
      type: integer
      format: int32
      multipleOf: 11

    MultipleOfLongValue:
      type: integer
      format: int64
      multipleOf: 22

    StringValue:
      type: string
      pattern: '[A-Za-z\d]*'
      minLength: 2
      maxLength: 10
      maximum: 249

    Email:
      type: string
      format: email