openapi: "3.0.0"
info: { }

paths: { }

components:
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
    themeParam:
      in: query
      name: theme
      required: false
      schema:
        type: string
        minLength: 2
        maxLength: 10
        default: theme0
        pattern: "[a-z]+\\d"
      description: The choosen theme.