openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      required:
        - id
        - externalId
        - user
        - city
      properties:
        id:
          $ref: "#/components/schemas/UserKey"
        externalId:
          type: integer
          format: int64
        user:
          type: string
          minLength: 7
          maxLength: 25
        birthday:
          type: string
          format: date
        city:
          type: string
        age:
          type: integer
          minimum: 15
          maximum: 49
        lastLogin:
          type: string
          format: date-time
        role:
          type: string
          enum: [ "Admin", "User", "Visitor" ]
        currencies:
          type: object
          additionalProperties:
            type: string
        interests:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                prio:
                  type: integer
        languages:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Language'
        hobbies:
          type: object
          additionalProperties:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              description:
                type: string
        data:
          description: 'Some user related data'

    UserGroup:
      properties:
        owner:
          $ref: "#/components/schemas/User"
        members:
          type: array
          minItems: 1
          maxItems: 5
          items:
            $ref: "#/components/schemas/User"
        languages:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string

    Language:
      required:
        - key
        - name
      properties:
        key:
          type: integer
        name:
          type: string

    Color:
      required:
        - colorKey
        - colorName
      properties:
        colorKey:
          type: integer
        colorName:
          type: string

    Car:
      allOf:
        - $ref: '#/components/schemas/Color'
        - type: object
          required:
            - model
          properties:
            model:
              type: string
            isCombi:
              type: boolean

    UserKey:
      type: string
      format: uuid
      description: Key for a user

