openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      required:
        - id
        - username
      properties:
        id:
          type: string
        username:
          type: string
          nullable: true
        email:
          type: string
          format: email
        phone:
          type: string
          nullable: true



