openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    ErrorMessage:
      required:
        - key
        - message
      properties:
        key:
          type: string
          enum:
            - A1
            - A2
        message:
          type: string
    Patient:
      minProperties: 2
      maxProperties: 3
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
          nullable: true
        surname:
          type: string
        age:
          type: integer
          nullable: true





