openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      required:
        - id
        - username
        - type
      properties:
        id:
          type: string
          minLength: 2
        username:
          type: string
        type:
          type: string
        age:
          type: integer
          format: int32
          minimum: 18
          maximum: 199
        email:
          type: string
          nullable: true
    Admin:
      required:
        - id
        - adminname
        - type
      properties:
        id:
          type: string
          minLength: 2
        adminname:
          type: string
        type:
          type: string
        level:
          type: integer
          format: int64
          minimum: 1
        color:
          type: string
          enum:
            - yellow
            - orange
            - red

    AdminOrUser:
      anyOf:
        - $ref: '#/components/schemas/Admin'
        - $ref: '#/components/schemas/User'

    AdminOrUserDiscriminator:
      anyOf:
        - $ref: '#/components/schemas/Admin'
        - $ref: '#/components/schemas/User'
      discriminator:
        propertyName: type

    InlinedAnyOf:
      type: object
      required:
        - adminOrUser
      properties:
        adminOrUser:
          anyOf:
            - $ref: '#/components/schemas/Admin'
            - $ref: '#/components/schemas/User'

    AnyOfMemberReference:
      anyOf:
        - $ref: '#/components/schemas/BaseAnyOfMemberReference'
        - type: object
          properties:
            name:
              type: string

    BaseAnyOfMemberReference:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ReferenceId'

    ReferenceId:
      type: string
      format: uuid






