openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      required:
        - ids
        - usernames
      properties:
        ids:
          type: array
          items:
            type: string
            nullable: true
            minLength: 6
            maxLength: 10
          minItems: 1
          maxItems: 2
        usernames:
          type: array
          items:
            type: string
            nullable: true
            minLength: 2
            maxLength: 4
          nullable: true
          minItems: 3
          maxItems: 4
        emails:
          type: array
          items:
            type: string
            nullable: true
            pattern: '[A-Za-z0-9]+@[A-Za-z0-9]+\.[a-z]+'
          minItems: 5
          maxItems: 6
        phones:
          type: array
          items:
            type: string
            nullable: true
          pattern: '\+41[0-9]{7}'
          minItems: 7
          maxItems: 8
          nullable: true